services:
  db:
    image: postgres:16-alpine
    container_name: messenger-db
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: messenger_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  